# Generated by Django 2.1.7 on 2019-02-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
            ],
        ),
        migrations.CreateModel(
            name='Shampoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='シャンプー名')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='メーカー')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='値段')),
            ],
        ),
        migrations.AddField(
            model_name='impression',
            name='shampoo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.Shampoo', verbose_name='シャンプー'),
        ),
    ]
